version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    docker:
     - image: cimg/node:12.13.1
    steps:
      - checkout
      - node/install-yarn:
        version: 1.22.21
      - node/install-packages:
          pkg-manager: yarn 
      - run: yarn lint
      - run: yarn coverage
workflows:
  build-and-test:
    jobs:
      - build-and-test
