version: 2.1

parameters:
  node-image-tag:
    type: string
    default: "12.13.1"
  yarn-version:
    type: string
    default: "1.22.21"
  resource-class:
    type: string
    default: "small"

orbs:
  node: circleci/node@5.1.1

jobs:
  clone-and-install:
    docker:
     - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - node/install-yarn:
          version: << pipeline.parameters.yarn-version >>
      - node/install-packages:
          pkg-manager: yarn 
workflows:
  build-and-test:
    jobs:
      - clone-and-install
      - node/run:
          name: lint
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: lint
      - node/run:
          name: coverage
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: coverage
