version: 2.1

parameters:
  node-image-tag:
    type: string
    default: "20.1.0"
  yarn-version:
    type: string
    default: "1.22.21"
  resource-class:
    type: string
    default: "small"

orbs:
  node: circleci/node@5.1.1
  coveralls: coveralls/coveralls@2.2.1

jobs:
  clone-and-install:
    docker:
     - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - node/install-yarn:
          version: << pipeline.parameters.yarn-version >>
      - node/install-packages:
          pkg-manager: yarn
  coverage:
    docker:
    - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - node/install-yarn:
          version: << pipeline.parameters.yarn-version >>
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Code Coverage
          command: yarn run coverage
      - run:
          name: Create Code Coverage lcov file
          command: yarn run nyc --reporter=text-lcov report > coverage.lcov
      - coveralls/upload:
          coverage_file: coverage.lcov

workflows:
  build-and-test:
    jobs:
      - clone-and-install
      - node/run:
          name: lint
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: lint
      - coverage:
          requires:
            - clone-and-install
